# Generated by Django 5.0.1 on 2024-01-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_area_proceso_delete_proyect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.area')),
            ],
        ),
    ]
