# Generated by Django 5.0.1 on 2024-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_historicoventa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='Producto',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
