# Generated by Django 5.0.1 on 2024-02-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_historicoventa_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoventa',
            name='Producto',
        ),
    ]
